gfont: 
    - "Montserrat:700"
    - "Open+Sans:400,400italic,700,700italic"

images:
    - division/images/death-to-stock-above-1.jpg
    - division/images/death-to-stock-above-2.jpg
    - division/images/death-to-stock-above-5.jpg
    - division/images/death-to-stock-above-10.jpg
    - division/images/death-to-stock-above-6.jpg
    - division/images/death-to-stock-above-7.jpg
    - division/images/death-to-stock-above-8.jpg
    - division/images/death-to-stock-above-9.jpg
